# Generated by Django 3.1.4 on 2020-12-31 17:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("news", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="news",
            options={
                "ordering": ["-created_at", "title"],
                "verbose_name": "Новость",
                "verbose_name_plural": "Новости",
            },
        ),
        migrations.RenameField(
            model_name="news",
            old_name="updates_at",
            new_name="updated_at",
        ),
    ]
